food_delivery/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index_page, name='index-page'),
    path('browsing/', views.browsing_page, name='browsing-page'),
    path('products/<str:store>/<str:product>', views.product_page, name='product-page'),
    path('stores/<str:store>/', views.store_page, name='store-page'),
    path('cart/<str:user>/', views.cart_page, name='cart-page'),
    path('profile/<str:user>/', views.profile_page, name='profile-page'),
    # ajax links
    path('add-cart/', views.cart_add, name='add-cart')
]

food_delivery/food_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

food_delivery/core/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from PIL import Image

from user.models import Customer
# Create your models here.
class Store(models.Model):
    store_help_text = 'Keep in mind you can only own one store at the moment'

    customer = models.OneToOneField(Customer, on_delete=models.CASCADE)
    store_name = models.CharField(max_length=250, help_text=store_help_text)
    location = models.CharField(max_length=500)
    slug = models.SlugField(blank=True, max_length=500)

    def __str__(self):
        return self.store_name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        self.slug = slugify(self.store_name)

    def get_absolute_url(self):
        return reverse('core:store-page', args=[self.slug])

class StoreProfile(models.Model):
    store = models.OneToOneField(Store, on_delete=models.CASCADE)
    store_profile = models.ImageField('Store profile photo', upload_to='store/profile', blank=True)
    store_cover = models.ImageField('Store cover photo', upload_to='store/cover', blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.store_profile)

        if img.width > 300 or img.height > 300:
            profile_size = (300, 300)
            img.thumbnail(profile_size)
            img.save(self.store_profile.path)

    def __str__(self):
        return f'{self.store.store_name} store'

class Product(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(blank=True, max_length=500)
    price = models.CharField(max_length=250)
    description = models.TextField(max_length=1000)
    create_date = models.DateTimeField()
    thumbnail = models.ImageField(upload_to='uploads')
    weight = models.DecimalField(max_digits=5, decimal_places=2, default=0, help_text='in kg')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        self.slug = slugify(self.name)
        # img = Image.open(self.thumbnail)

        # if img.width > 300 or img.height > 300:
            # output = (300, 300)
            # img.thumbnail(output)
            # img.save(self.thumbnail.path)


class Category(models.Model):
    name = models.CharField(max_length=100)
    thumbnail = models.ImageField(upload_to='categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

class ProductCategory(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category)

    def __str__(self):
        return self.product.name

    def get_absolute_url(self):
        return reverse('core:product-page', args=[self.product.store.slug, self.product.slug])

    class Meta:
        verbose_name_plural = 'Products has Categories'

class Stock(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    store = models.OneToOneField(Store, on_delete=models.CASCADE)
    quantity = models.IntegerField()


    def __str__(self):
        if self.quantity <= 0:
            return f'{self.product.name} is out of stock'
        return f'{self.product.name} has stock'

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)


    def __str__(self):
        return f'{self.customer.get_fullname} cart'

class CustomerShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=400)
    phone = models.IntegerField()
    house_no = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=15)
    province = models.CharField(max_length=60)
    city_municipality = models.CharField(max_length=80)
    barangay = models.CharField(max_length=50)
    note = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return f'{self.customer.get_fullname} address'

    class Meta:
        verbose_name_plural = 'Customer\'s Shipping Addresses'

class Order(models.Model):
    STATUS = [
        ('Pending', 'Pending'),
        ('Ready to Pickup', 'Ready to Pickup'),
        ('On its way', 'On its way'),
        ('Delivered', 'Delivered')
    ]

    customer = models.ForeignKey(CustomerShippingAddress, on_delete=models.CASCADE)
    order_date = models.DateTimeField()
    order_status = models.CharField(max_length=20, choices=STATUS)

    def __str__(self):
        return f'{self.customer.customer.get_fullname} order'

class OrderDetail(models.Model):
    OPTIONS = [
        ('Pickup',  'Pickup'),
        ('Online Payment', 'Online Payment'),
        ('COD', 'COD')
    ]

    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    options = models.CharField(max_length=25, choices=OPTIONS)

    def __str__(self):
        return f'{self.order.customer.customer.get_fullname} order detail'

food_delivery/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.utils.text import slugify
import json

from .models import  Store, StoreProfile, ProductCategory, Product, Cart
# Create your views here.

# page views !
def index_page(request):
    return render(request, 'core/index.html')


def browsing_page(request):
    stores = Store.objects.all()
    products = ProductCategory.objects.all()
    context = {
        'stores': stores,
        'products': products
    }

    return render(request, 'core/browsing.html', context)

def product_page(request, store, product):
    obj = Store.objects.get(slug=store)

    product = Product.objects.get(slug=product, store=obj)

    obj = ProductCategory.objects.get(product=product)

    context = {
        "obj": obj,
    }
    return render(request, 'core/product.html', context)

def cart_page(request, user):
    return render(request, 'core/cart.html')

def profile_page(request, user):
    return render(request, 'core/profile.html')

def store_page(request, store):
    # most sell product
    obj = Store.objects.get(slug=store)

    store = StoreProfile.objects.get(store=obj)
    products = ProductCategory.objects.filter(product__store=store.store)
    context = {
        'store': store,
        'products': products,
    }

    return render(request, 'core/store.html', context)

# page views!

# ajax part!
def cart_add(request):

    payload = json.loads(request.body.decode('utf-8'))

    product_slug = slugify(payload.get('productName'))
    product_name = payload.get('productName')
    product_sold = payload.get('productSold')
    quantity = int(payload.get('productQuantity'))
    if request.user.is_authenticated:
        store_name = Store.objects.get(slug=product_sold)
        product = Product.objects.get(slug=product_slug, store=store_name)
        try:
            cart_check = Cart.objects.get(product=product, customer=request.user)
            cart_check.quantity += quantity
            cart_check.save()
        except Cart.DoesNotExist:
            cart = Cart.objects.create(product=product, customer=request.user, quantity=quantity)

        return JsonResponse({'message': 'Product added to your cart', 'isLogged': True})

    # data = {
        # "productName": product_name,
        # "productSold": product_sold,
        # "quantity": quantity
    # }

    # response = JsonResponse({'message': 'Not Logged in'})
    # response.set_cookie('cart', data)
    # if 'cart' in response.cookies:
        # response.cookies['cart']['samesite'] = 'Lax'
        # response.cookies['cart']['httponly'] = True
    return JsonResponse({'message': 'Not Logged in',  'islogged': False})

food_delivery/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&family=Montserrat:ital,wght@0,500;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
     <link rel="stylesheet" href="{% static 'core/css/style.css' %}" media="all">
    <title>Document</title>

    {% block style %}

    {% endblock %}
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
    <script src="{% static 'core/js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</html>

food_delivery/core/templates/core/browsing.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container browsing__container">
        <h2 class="stores__title">
          Stores
        </h2>
        <div class="stores">
            <section id="minimal-statistics">
              <div class="row">
                {% for store in stores %}
                  <div class="col-lg-3 col-sm-6 col-12 mb-4">
                    <div class="card">
                      <div class="card-content">
                        <div class="card-body">
                          <div class="media d-flex">
                            <div class="media-body text-left">
                              <h3 class="danger">{{ store.store_name }}</h3>
                              <span>{{ store.customer.get_fullname }}</span>
                              <br>

                              <a href="{{ store.get_absolute_url }}" class="btn btn-primary mt-3">Shop</a>
                            </div>
                            <div class="align-self-center">
                              <i class="fas fa-store store__icon"></i>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </section>
        </div>

        <div class="products">
          <h2 class="products__title">
            Products
          </h2>
            {% include 'core/product_card.html' %}
        </div>
    </div>
{% endblock %}

food_delivery/core/templates/core/cart.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Cart Page</h1>
    <p>I love and hate programming</p>
{% endblock %}

food_delivery/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block style %}
  <style>
    body {
      overflow: hidden;
    }
  </style>
{% endblock %}

{% block content %}
    <div class="container-home">
      <div class="bg">
          <div class="background">
            <div class="background__overlay"></div>

            {% load static %}
            <img class="background__image" src="{% static 'core/assets/bg.jpg' %}" alt="">
          </div>
      </div>

      <!-- search bar use ajax here -->

      <div class="srch">
          <div class="search">
            <div class="headers">
                <div class="headers__text">
                  <h1 class="headers__title">Foody</h2>
                  <p class="headers__sub">Foody helps you save time by buying high quality food without leaving your home</p>
                </div>
            </div>
            <form action="" method="get">
                <div class="search__custom">
                  <input id="search" class="search__text" type="text" name="search" placeholder="Find your food to get started">
                  {% comment %}<input class="search__btn " type="submit"><i class="fas fa-search"></input>{% endcomment %}
                  <button class="search__btn"><i class="fas fa-search"></i></button>
                </div>
            </form>

            <a class="explore" href="{% url 'core:browsing-page' %}">Explore</a>
          </div>
      </div>
    </div>
{% endblock %}

food_delivery/core/templates/core/product.html
{% extends 'core/base.html' %}


{% block content %}
<p class="product__success">Added to cart</p>
<div class="container product__container">
    <div class="sproduct row">
      <div class="left col-xl-6 col-lg-6 col-sm-12">
        <div class="sproduct__img">
          <img src="{{ obj.product.thumbnail.url  }}" alt="">
        </div>
      </div>
      <div class="right ccolxl-6 col-lg-6 col-sm-12">
        <div class="sproduct__details">

          <h1 class="sproduct__title">
            {{ obj.product.name  }}
          </h1>

         <div class="sproduct__tally">
            <h1 class="sproduct__price">
              ₱{{ obj.product.price }}
            </h1>
         </div>

          <p class="sproduct__description">
            {{ obj.product.description }}
          </p>

          <div class="sproduct__category">
            <p class="category__text">Category:
              {% for category in obj.category.all %}

              <span class="category__title">{{ category.name }}</span>
              {% endfor %}
            </p>
            <p id="sproduct__sname">Sold By: <span class="product__seller">{{ obj.product.store.store_name }}</span></p>
          </div>

          <div class="sproduct__cart">
              <div class="d-flex">
                <div class="cart__increase"><i class="fas fa-arrow-up"></i></div>
                <input id="quantity" type="number" name="quantity" value="1" class="sproduct__quantity">
                <div class="cart__decrease"><i class="fas fa-arrow-down"></i></div>
              </div>
              <input id="sproduct__sold" type="hidden" name="" value="{{ obj.product.store.slug  }}">
              <button id="add-to-cart" class="btn-primary cart__btn"><i class="fas fa-cart-plus"></i>Add to Cart</button>
          </div>
        </div>

      </div>
    </div>
</div>

{% endblock %}

food_delivery/core/templates/core/product_card.html
<div class="row products__row">
  {% for prod in products %}
    <div class="col-xl-3 col-sm-6 col-12 mb-4 card card--custom" style="width: 18rem;">
      <div class="card__img">
        <img class="card-img-top" src="{{ prod.product.thumbnail.url }}" alt="Card image cap">
      </div>
      <div class="card-body card__body--column">
        <div class="card__text">
          <h5 class="card-title">{{ prod.product.name|truncatechars:43 }}</h5>
          <p class="product__price">₱ {{ prod.product.price }}</p>
        </div>
        <div class="card__btn">
        <p>Ratings here</p>
        <a href="{{ prod.get_absolute_url }}" class="btn btn-primary card-read">READ MORE</a>
        <a href="{{ prod.get_absolute_url }}" class="btn card-add"><i class="fas fa-cart-plus"></i></a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

food_delivery/core/templates/core/store.html
{% extends 'core/base.html' %}

{% block content %}
<div class="store-container">
  <div class="store__header">
    <div class="store__cover">
        <img class="store__cover-img" src="{{ store.store_cover.url }}" alt="">

    </div>

    <div class="store__relative">
      <div class="store__profile">
        <div>
          <img class="store__profile-img" src="{{ store.store_profile.url }}" alt="">
        </div>
        <h2 class="store__profile-text text-center">{{ store.store.store_name }}</h2>
      </div>
    </div>
  </div>


  <div class="store__product">

  <div class="store__best">
    <div class="container pb-4">
      {% if products %}
        <h1>Most Popular</h1>
        {% include 'core/product_card.html' %}
      {% else %}
        <div class="store__none">
          This store has not yet posted any products to sell
        </div>
      {% endif %}
    </div>
  </div>

  </div>
</div>
{% endblock %}